### ISSUE TITLE
Cannot print large html file 

### ISSUE THREAD

**Issue by anotatta** [Sicos1977/ChromiumHtmlToPdf#109]
The file is about 6 MB, just simple html, no javascript.
Thanks for help.

Log File:
2023-05-03T11:47:16.504 - Resetting Chrome arguments to default
2023-05-03T11:47:16.509 - Adding Chrome argument '--headless'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-gpu'
2023-05-03T11:47:16.511 - Adding Chrome argument '--hide-scrollbars'
2023-05-03T11:47:16.511 - Adding Chrome argument '--mute-audio'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-background-networking'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-background-timer-throttling'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-default-apps'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-extensions'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-hang-monitor'
2023-05-03T11:47:16.511 - Adding Chrome argument '--disable-prompt-on-repost'
2023-05-03T11:47:16.512 - Adding Chrome argument '--disable-sync'
2023-05-03T11:47:16.512 - Adding Chrome argument '--disable-translate'
2023-05-03T11:47:16.512 - Adding Chrome argument '--metrics-recording-only'
2023-05-03T11:47:16.512 - Adding Chrome argument '--no-first-run'
2023-05-03T11:47:16.512 - Adding Chrome argument '--disable-crash-reporter'
2023-05-03T11:47:16.518 - Adding Chrome argument '--remote-debugging-port="0"'
2023-05-03T11:47:16.519 - Adding Chrome argument '--window-size="1366,768"'
2023-05-03T11:47:16.572 - Updating Chrome argument '--window-size="1366,768"' with value '1366,768'
2023-05-03T11:47:16.625 - Starting Chrome from location 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files (x86)\Google\Chrome\Application'
2023-05-03T11:47:16.626 - "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless --disable-gpu --hide-scrollbars --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --disable-crash-reporter --remote-debugging-port="0" --window-size="1366,768"
2023-05-03T11:47:16.687 - Chrome process started
2023-05-03T11:47:21.180 - Received Chrome error data: 'DevTools listening on ws://127.0.0.1:1664/devtools/browser/8198abd5-3a90-478b-85d0-95bba4f0bfd1'
2023-05-03T11:47:21.182 - Connecting to dev protocol on uri 'ws://127.0.0.1:1664/devtools/browser/8198abd5-3a90-478b-85d0-95bba4f0bfd1'
2023-05-03T11:47:21.188 - Creating new websocket connection to url 'ws://127.0.0.1:1664/devtools/browser/8198abd5-3a90-478b-85d0-95bba4f0bfd1'
2023-05-03T11:47:21.199 - Opening websocket connection with a timeout of 30 seconds
2023-05-03T11:47:22.604 - Websocket opened
2023-05-03T11:47:23.817 - Creating new websocket connection to url 'ws://127.0.0.1:1664/devtools/page/744088D549328097FF0A3B7287FC1244'
2023-05-03T11:47:23.817 - Opening websocket connection with a timeout of 30 seconds
2023-05-03T11:47:23.875 - Websocket opened
2023-05-03T11:47:23.876 - Connected to dev protocol
2023-05-03T11:47:23.876 - Chrome started
2023-05-03T11:47:23.876 - Loading file E:\Documents\06wip\00Pali\03MyDict\dpd\content.03.b.html
2023-05-03T11:47:23.888 - Enabling caching
2023-05-03T11:47:24.696 - The 'Page.frameNavigated' event has been fired, waiting for the 'Page.lifecycleEvent' with name 'networkIdle'
2023-05-03T11:47:48.204 - The 'Page.lifecycleEvent' with param name 'DomContentLoaded' has been fired, the dom content is now loaded and parsed, waiting for stylesheets, images and sub frames to finish loading
2023-05-03T11:47:55.757 - The 'Page.lifecycleEvent' event with name 'networkIdle' has been fired, the page is now fully loaded
2023-05-03T11:47:55.950 - File loaded
2023-05-03T11:47:55.951 - Converting to PDF
2023-05-03T11:48:26.872 - An error occurred: 'Printing failed'
2023-05-03T11:48:26.877 - Error: Conversion failed ... did not get the expected response from Chrome, response '{"id":7,"error":{"code":-32000,"message":"Printing failed"}}'
'
2023-05-03T11:48:26.880 - Closing Chrome browser gracefully
2023-05-03T11:48:26.891 - Disposing websocket connection to url 'ws://127.0.0.1:1664/devtools/page/744088D549328097FF0A3B7287FC1244'
2023-05-03T11:48:26.923 - Closing websocket
2023-05-03T11:48:26.929 - Websocket connection disposed
2023-05-03T11:48:26.929 - Disposing websocket connection to url 'ws://127.0.0.1:1664/devtools/browser/8198abd5-3a90-478b-85d0-95bba4f0bfd1'
2023-05-03T11:48:26.929 - Closing websocket
2023-05-03T11:48:26.929 - Websocket connection disposed
2023-05-03T11:48:27.406 - Chrome closed gracefully
2023-05-03T11:48:28.010 - [null] -    at ChromeHtmlToPdfLib.Browser.PrintToPdf(Stream outputStream, PageSettings pageSettings, CountdownTimer countdownTimer) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Browser.cs:line 602
   at ChromeHtmlToPdfLib.Converter.Convert(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Converter.cs:line 1296
   at ChromeHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Converter.cs:line 1404
   at ChromeHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Converter.cs:line 1448
   at ChromeHtmlToPdfConsole.Program.Convert(Options options) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfConsole\Program.cs:line 346
   at ChromeHtmlToPdfConsole.Program.Main(String[] args) in D:\Progsoft\_GitHub_\ChromeHtmlToPdf\ChromeHtmlToPdfConsole\Program.cs:line 135, Conversion failed ... did not get the expected response from Chrome, response '{"id":7,"error":{"code":-32000,"message":"Printing failed"}}'

**Comment by Sicos1977** [comment]
WHat happens if you just open the file in Google Chrome and then save it as PDF?

**Comment by anotatta** [comment]
It took a few minutes to open, much looonger to print.

**Comment by Sicos1977** [comment]
Then I guess it is somekind of timeout issue somewhere because it takes so long.
