### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by Ric-Carey** [Sicos1977/ChromiumHtmlToPdf#134]
Hey,

Love this tool, your work on it is much appreciated.

More of a comment than an issue. (may want to include in readme maybe?) I just wanted to flag, incase anyone else has this same issue.

We had version 2.0.26 running on our website, which has worked happily for the last three or four years. 

Chrome decided to update overnight to version 119.0.6045.106 – which then made the Console App get stuck trying to open the webpage to render. The website would wait for the process to complete, which meant that the process would just continue until the site timed out. I tested with v118 of Chrome and it still worked. 

I’ve upgraded to version 3.0.0 which is compatible with the latest version of Chrome (above). 

I tried to use the 4.1.2 console app (Windows 11 and Windows Server 2019) but in both, the console app errors (see below).
(I tried adding –timeout parameter, but had no luck).

Not sure if the new v4 version is fully stable yet?

Many thanks,
Ric

2023-11-03T11:18:24.650 - Google Chrome exited unexpectedly, arguments used: --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2023-11-03T11:18:24.650 - Process id: 27292
2023-11-03T11:18:24.652 - Process exit time: 2023-11-03T11:18:24.646
2023-11-03T11:18:24.656 - Error: Google Chrome exited unexpectedly
'
2023-11-03T11:18:24.661 - Google Chrome closed gracefully
2023-11-03T11:18:24.684 -    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 729
   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1407
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in D:\Progrsion 3.0.0 which is compatible with the latest version of Chrome (above).

**Comment by Sicos1977** [comment]
It probably has to do with the new headless mode that is now the default. For some unknown reason this will not always work. Because of this I added an option that you can use to switch back to the old headless mode. In most cases this fixes the issue.

I really don't know why this sometimes is the case. I use it with the new headless mode and don't have any problems at all

**Comment by Ric-Carey** [comment]
Ah yeah cheers adding --use-old-headless-mode true and it worked on v4.
