### ISSUE TITLE
Google Chrome exited unexpectedly

### ISSUE THREAD

**Issue by sbernesto** [Sicos1977/ChromiumHtmlToPdf#138]
Hi, 

In the past months it had been working well for me, but today when I need it I get an unexpected error

I thought it was because I was using Windows 11, but I already tried Windows 10 and I have the same error

[https://pastebin.com/z1Ai0dsZ](url)

`C:\ChromiumHtmlToPdf>ChromiumHtmlToPdfConsole --input https://www.google.com --output c:\google.pdf
2024-01-03T12:56:42.014 - Resetting Chromium arguments to default
2024-01-03T12:56:42.026 - Adding Chromium argument '--headless=new'
2024-01-03T12:56:42.027 - Adding Chromium argument '--block-new-web-contents'
2024-01-03T12:56:42.027 - Adding Chromium argument '--hide-scrollbars'
2024-01-03T12:56:42.027 - Adding Chromium argument '--disable-domain-reliability'
2024-01-03T12:56:42.027 - Adding Chromium argument '--disable-sync'
2024-01-03T12:56:42.028 - Adding Chromium argument '--mute-audio'
2024-01-03T12:56:42.028 - Adding Chromium argument '--disable-background-networking'
2024-01-03T12:56:42.028 - Adding Chromium argument '--disable-background-timer-throttling'
2024-01-03T12:56:42.028 - Adding Chromium argument '--disable-default-apps'
2024-01-03T12:56:42.028 - Adding Chromium argument '--disable-extensions'
2024-01-03T12:56:42.029 - Adding Chromium argument '--disable-hang-monitor'
2024-01-03T12:56:42.029 - Adding Chromium argument '--disable-prompt-on-repost'
2024-01-03T12:56:42.029 - Adding Chromium argument '--metrics-recording-only'
2024-01-03T12:56:42.029 - Adding Chromium argument '--no-first-run'
2024-01-03T12:56:42.029 - Adding Chromium argument '--no-default-browser-check'
2024-01-03T12:56:42.029 - Adding Chromium argument '--enable-automation'
2024-01-03T12:56:42.030 - Adding Chromium argument '--no-pings'
2024-01-03T12:56:42.030 - Adding Chromium argument '--noerrdialogs'
2024-01-03T12:56:42.030 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-01-03T12:56:42.032 - Adding Chromium argument '--remote-debugging-port="0"'
2024-01-03T12:56:42.032 - Adding Chromium argument '--window-size="1366,768"'
2024-01-03T12:56:42.050 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-01-03T12:56:42.080 - Starting Google Chrome from location 'C:\Program Files\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files\Google\Chrome\Application'
2024-01-03T12:56:42.080 - "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-01-03T12:56:42.111 - Google Chrome process started
2024-01-03T12:56:42.255 - Google Chrome exited unexpectedly, arguments used: --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-01-03T12:56:42.255 - Process id: 10640
2024-01-03T12:56:42.265 - Process exit time: 2024-01-03T12:56:42.247
2024-01-03T12:56:42.268 - Error: Google Chrome exited unexpectedly
'
2024-01-03T12:56:42.274 - Google Chrome closed gracefully
2024-01-03T12:56:42.319 -    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 729
   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1407
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1826
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1901
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1661
   at ChromiumHtmlToPdfConsole.Program.Convert(Options options) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole\Program.cs:line 368
   at ChromiumHtmlToPdfConsole.Program.Main(String[] args) in D:\Progsoft\_GitHub_\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole\Program.cs:line 143, Google Chrome exited unexpectedly`

**Comment by Sicos1977** [comment]
Did you try it with the old headless mode?

**Comment by sbernesto** [comment]
Thank you, its works
