### ISSUE TITLE
Getting error "Error: Google Chrome exited unexpectedly"

### ISSUE THREAD

**Issue by vlasto77** [Sicos1977/ChromiumHtmlToPdf#162]
Hi,

I'm getting an error 

> ChromiumHtmlToPdf_4_2_1\ChromiumHtmlToPdfConsole.exe --input ./ps.html --output ./ps.pdf

2024-07-29T14:33:44.276 - Resetting Chromium arguments to default
2024-07-29T14:33:44.293 - Adding Chromium argument '--headless=new'
2024-07-29T14:33:44.304 - Adding Chromium argument '--block-new-web-contents'
2024-07-29T14:33:44.304 - Adding Chromium argument '--hide-scrollbars'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-domain-reliability'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-sync'
2024-07-29T14:33:44.304 - Adding Chromium argument '--mute-audio'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-background-networking'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-background-timer-throttling'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-default-apps'
2024-07-29T14:33:44.304 - Adding Chromium argument '--disable-extensions'
2024-07-29T14:33:44.305 - Adding Chromium argument '--disable-hang-monitor'
2024-07-29T14:33:44.305 - Adding Chromium argument '--disable-prompt-on-repost'
2024-07-29T14:33:44.305 - Adding Chromium argument '--metrics-recording-only'
2024-07-29T14:33:44.305 - Adding Chromium argument '--no-first-run'
2024-07-29T14:33:44.305 - Adding Chromium argument '--no-default-browser-check'
2024-07-29T14:33:44.305 - Adding Chromium argument '--enable-automation'
2024-07-29T14:33:44.305 - Adding Chromium argument '--no-pings'
2024-07-29T14:33:44.305 - Adding Chromium argument '--noerrdialogs'
2024-07-29T14:33:44.305 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-07-29T14:33:44.309 - Adding Chromium argument '--remote-debugging-port="0"'
2024-07-29T14:33:44.309 - Adding Chromium argument '--window-size="1366,768"'
2024-07-29T14:33:44.313 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-07-29T14:33:44.327 - Starting Google Chrome from location 'C:\Program Files\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files\Google\Chrome\Application'
2024-07-29T14:33:44.327 - "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-07-29T14:33:44.337 - Google Chrome process started
2024-07-29T14:33:44.402 - Google Chrome exited unexpectedly, arguments used: --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-07-29T14:33:44.402 - Process id: 19340
2024-07-29T14:33:44.403 - Process exit time: 2024-07-29T14:33:44.398
2024-07-29T14:33:44.404 - Error: Google Chrome exited unexpectedly
'
2024-07-29T14:33:44.407 - Google Chrome closed gracefully
2024-07-29T14:33:44.424 -    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 747
   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1418
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1839
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1906
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfLib\Converter.cs:line 1665
   at ChromiumHtmlToPdfConsole.Program.Convert(Options options) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole\Program.cs:line 360
   at ChromiumHtmlToPdfConsole.Program.Main(String[] args) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole\Program.cs:line 140, Google Chrome exited unexpectedly

Any idea how to solve this?

**Comment by Sicos1977** [comment]
What Chrome version are you using?

**Comment by Sicos1977** [comment]
Try adding this flag and see if that makes any difference

`--disable-features=PrintCompositorLPAC`

**Comment by vlasto77** [comment]
It doesn't help. Still the same issue,

**Comment by Sicos1977** [comment]
You can try disabling the new headless mode, this will sometimes also make a difference. You can also turn on Chromium debug logging to see if this gives you a clue why you get the error.

**Comment by vlasto77** [comment]
Disabling headless mode doesn't help. As well as there is nothing in the debu logs. With a headless mode the browser windows open and browser stays opened although I'm getting the error message above. I cloned the repo and try to debug it, and I found that OnChromiumProcessOnExited is called althoug browser is running. And this happens not just with Chrome, but also when using Edge. It behaves exactly the same. Disabling OnChromiumProcessOnExited gives me a timeout error when connecting to DevTools.

**Comment by Sicos1977** [comment]
When starting the lib tries to find a dev protocol file that has the port in it that is needed to connect to the headless engine.

**Comment by vlasto77** [comment]
Setting '--user-data-dir' fixed the problem on my Windows machine. At least for Chrome. Edge still doesn't work. However it didn't help for my docket container with ubuntu.

**Comment by vlasto77** [comment]
This solved issue on docker container
`
  converter.AddChromiumArgument("--disable-dev-shm-usage");
  converter.AddChromiumArgument("--disable-features=PrintCompositorLPAC");
  converter.UseOldHeadlessMode = true;
`

**Comment by tomasherceg** [comment]
Just confirming that the same workaround works on Windows & IIS too.
