### ISSUE TITLE
Conversion fails on Chrome 130

### ISSUE THREAD

**Issue by wijnsema** [Sicos1977/ChromiumHtmlToPdf#172]
I used this library for a couple of months, worked pretty well, thanks for the effort.

Since a couple of days/weeks the conversion fails. I think it is related to new Chrome 130, now I am using 130.0.6723.91

I get following errors: 

**Object reference not set to an instance of an object.**

at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken)   at ... my code

Above error is with 
`converter.AddChromiumArgument("--headless=old");`

When I remove this headless argument (every default) the error changes to"

**Google Chrome exited unexpectedly**

at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken)   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken)   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken)   ... my code

**Comment by wijnsema** [comment]
Hi @Sicos1977, hi Kees, any updates on this? Is this indeed caused by version 130?
Do you want me to do some more testing?

**Comment by Sicos1977** [comment]
I have no idea why it fails for you; I use Edge version 130 on a Windows 2019 server and that works without any problems.

Try adding this flag and see if that makes any difference --> `--disable-features=PrintCompositorLPAC`

If not than enable this flag for extra debug logging

```c#
    /// <summary>
    ///     Enables Chromium logging;<br/>
    ///     - The output will be saved to the file <b>chrome_debug.log</b> in Chrome's user data directory<br/>
    ///     - Logs are overwritten each time you restart chrome<br/>
    /// </summary>
    /// <remarks>
    ///     If the environment variable CHROME_LOG_FILE is set, Chrome will write its debug log to its specified location.<br/>
    ///     Example: Setting CHROME_LOG_FILE to "chrome_debug.log" will cause the log file to be written to the Chrome process's<br/>
    ///     current working directory while setting it to "D:\chrome_debug.log" will write the log to the root of your computer's D: drive.
    /// </remarks>
    public bool EnableChromiumLogging { get; set; }
```

**Comment by wijnsema** [comment]
Tried the following:

- --disable-features=PrintCompositorLPAC: same error
- Build the console app from your source (no code changes), used your example conversion (google.nl), same error
- Build the console app on a 'random' Windows 11 laptop, same error
- Copied console app to Windows Server 2022 machine with Edge installed, same error

Using ```EnableChromiumLogging ``` didn't reveal any more information than before.

**Comment by wijnsema** [comment]
One other change which might be relevant: The console app is now targeting net8.0, as is my code, whereas is the recent past I was using net7.0. 

I changed one or two months ago, it's well possible that at this time the conversion started to fail.

**Comment by MaceWindu** [comment]
@wijnsema could you provide information on used version of `ChromiumHtmlToPdf` and maybe build current master in debug to have line numbers in error stack?

**Comment by wijnsema** [comment]
I'm using latest version 4.2.10, same as master branch.

I stepped through the code, nothing out the ordinary. Only somewhere in the Edge process something goes wrong, and only shows: **Error: Microsoft Edge exited unexpectedly**

This is the log output:

2024-11-09T22:56:40.291 - Resetting Chromium arguments to default
2024-11-09T22:56:40.319 - Adding Chromium argument '--headless=new'
2024-11-09T22:56:40.328 - Adding Chromium argument '--block-new-web-contents'
2024-11-09T22:56:40.328 - Adding Chromium argument '--hide-scrollbars'
2024-11-09T22:56:40.328 - Adding Chromium argument '--disable-domain-reliability'
2024-11-09T22:56:40.328 - Adding Chromium argument '--disable-sync'
2024-11-09T22:56:40.329 - Adding Chromium argument '--mute-audio'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-background-networking'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-background-timer-throttling'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-default-apps'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-extensions'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-hang-monitor'
2024-11-09T22:56:40.329 - Adding Chromium argument '--disable-prompt-on-repost'
2024-11-09T22:56:40.329 - Adding Chromium argument '--metrics-recording-only'
2024-11-09T22:56:40.329 - Adding Chromium argument '--no-first-run'
2024-11-09T22:56:40.329 - Adding Chromium argument '--no-default-browser-check'
2024-11-09T22:56:40.329 - Adding Chromium argument '--enable-automation'
2024-11-09T22:56:40.329 - Adding Chromium argument '--no-pings'
2024-11-09T22:56:40.329 - Adding Chromium argument '--noerrdialogs'
2024-11-09T22:56:40.329 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-11-09T22:56:40.332 - Adding Chromium argument '--remote-debugging-port="0"'
2024-11-09T22:56:40.332 - Adding Chromium argument '--window-size="1366,768"'
2024-11-09T22:56:40.989 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-11-09T22:56:40.990 - Adding Chromium argument '--disk-cache-dir="c:\lib"'
2024-11-09T23:00:08.187 - Creating temp directory 'C:\Users\wijns\AppData\Local\Temp\8a737786-4dbb-46ce-b394-0b17020824f1'
2024-11-09T23:00:18.215 - Setting cache directory to 'c:\lib' with a size of 1 GB
2024-11-09T23:00:18.215 - Setting image load timeout to '15000' milliseconds
2024-11-09T23:00:36.954 - Opening stream to file 'c:\lib\index.html'
2024-11-09T23:00:37.192 - Sanitizing HTML
2024-11-09T23:00:37.238 - Removing tag 'META', reason 'NotAllowedTag'
2024-11-09T23:00:37.240 - Removing tag 'META', reason 'NotAllowedTag'
2024-11-09T23:00:37.240 - Removing tag 'TITLE', reason 'NotAllowedTag'
2024-11-09T23:00:37.242 - Removing attribute 'id' from tag 'DIV', reason 'NotAllowedAttribute'
2024-11-09T23:00:37.257 - HTML sanitized
2024-11-09T23:00:37.258 - Adding url 'file:///C:/Users/wijns/AppData/Local/Temp/8a737786-4dbb-46ce-b394-0b17020824f1/9b5a67e4-e17a-442a-bb46-c03412bab2d7.htm' to the safe url list
2024-11-09T23:00:37.259 - Writing sanitized webpage to 'C:\Users\wijns\AppData\Local\Temp\8a737786-4dbb-46ce-b394-0b17020824f1\9b5a67e4-e17a-442a-bb46-c03412bab2d7.htm'
2024-11-09T23:00:37.264 - Sanitized webpage written
2024-11-09T23:01:02.358 - Sanitization was successful changing input uri 'file:///c:/lib/index.html' to 'file:///C:/Users/wijns/AppData/Local/Temp/8a737786-4dbb-46ce-b394-0b17020824f1/9b5a67e4-e17a-442a-bb46-c03412bab2d7.htm'
2024-11-09T23:02:39.021 - Opening stream to file 'C:\Users\wijns\AppData\Local\Temp\8a737786-4dbb-46ce-b394-0b17020824f1\9b5a67e4-e17a-442a-bb46-c03412bab2d7.htm'
2024-11-09T23:02:39.023 - DPI settings for image, x: '96' and y: '96'
2024-11-09T23:02:39.063 - Validating all images if they need to be rotated and if they fit the page
2024-11-09T23:04:04.601 - Starting Microsoft Edge from location 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe' with working directory 'C:\Program Files (x86)\Microsoft\Edge\Application'
2024-11-09T23:04:07.500 - "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768" --disk-cache-dir="c:\lib"
2024-11-09T23:06:32.542 - Microsoft Edge process started
2024-11-09T23:07:12.252 - Microsoft Edge exited unexpectedly, arguments used: --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768" --disk-cache-dir="c:\lib"
Process id: 88616
Process exit time: 11/09/2024 23:06:21
2024-11-09T23:08:31.560 - Error: Microsoft Edge exited unexpectedly
'
2024-11-09T23:08:31.568 - Deleting temporary folder 'C:\Users\wijns\AppData\Local\Temp\8a737786-4dbb-46ce-b394-0b17020824f1'
2024-11-09T23:08:31.651 - Microsoft Edge closed gracefully
2024-11-09T23:08:31.671 -    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 785
   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1477
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1906
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1973
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1732
   at ChromiumHtmlToPdfConsole.Program.Convert(Options options) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\Program.cs:line 353
   at ChromiumHtmlToPdfConsole.Program.Main(String[] args) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\Program.cs:line 131, Microsoft Edge exited unexpectedly

C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\bin\Debug\net8.0\ChromiumHtmlToPdfConsole.exe (process 31436) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

**Comment by Sicos1977** [comment]
You could try to run with just the bare minimum of parameters

--headless=new
--no-first-run
--remote-debugging-port="0"'

**Comment by wijnsema** [comment]
Sorry, no change:

C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\bin\Debug\net8.0>ChromiumHtmlToPdfConsole --input c:\lib\index.html --output c:\lib\index.pdf
2024-11-10T14:07:19.185 - Resetting Chromium arguments to default
2024-11-10T14:07:19.208 - Adding Chromium argument '--headless=new'
2024-11-10T14:07:19.217 - Adding Chromium argument '--no-first-run'
2024-11-10T14:07:19.220 - Adding Chromium argument '--remote-debugging-port="0"'
2024-11-10T14:07:19.237 - Starting Microsoft Edge from location 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe' with working directory 'C:\Program Files (x86)\Microsoft\Edge\Application'
2024-11-10T14:07:19.238 - "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --headless=new --no-first-run --remote-debugging-port="0"
2024-11-10T14:07:19.246 - Microsoft Edge process started
2024-11-10T14:07:19.302 - Microsoft Edge exited unexpectedly, arguments used: --headless=new --no-first-run --remote-debugging-port="0"
Process id: 88608
Process exit time: 11/10/2024 14:07:19
2024-11-10T14:07:19.303 - Error: Microsoft Edge exited unexpectedly
'
2024-11-10T14:07:19.305 - Microsoft Edge closed gracefully
2024-11-10T14:07:19.319 -    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadlessAsync(CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 785
   at ChromiumHtmlToPdfLib.Converter.ConvertAsync(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1477
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1906
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdfAsync(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger, CancellationToken cancellationToken) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1973
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfLib\Converter.cs:line 1732
   at ChromiumHtmlToPdfConsole.Program.Convert(Options options) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\Program.cs:line 353
   at ChromiumHtmlToPdfConsole.Program.Main(String[] args) in C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\Program.cs:line 131, Microsoft Edge exited unexpectedly

C:\Projects\ChromiumHtmlToPdf-master\ChromiumHtmlToPdfConsole\bin\Debug\net8.0>

**Comment by abeninski** [comment]
Doesn't work for me with latest chrome. I am using latest library and Chrome is latest as well. 
```Google Chrome exited unexpectedly```

**Comment by Sicos1977** [comment]
I think the Chromium project removed the old headless mode, have to check this and if so remove the UseOldHeadlessmode flag.

**Comment by Sicos1977** [comment]
https://developer.chrome.com/blog/removing-headless-old-from-chrome

**Comment by MaceWindu** [comment]
Yes, it was removed in chrome 132+. Maybe instead remove it makes sense to mark `UseOldHeadlessMode` obsoleted, so it still could be used with older versions for some time

**Comment by Sicos1977** [comment]
I think I just gonna remove it instead... why would you want to use an old Chrome or Edge version? At the company where I'm working security is always pushing me to update Chrome. 

People always can keep using an older version of ChromiumHtmlToPdf if they want to use an older Chromium version
