### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by fabioren** [Sicos1977/ChromiumHtmlToPdf#180]
I'm trying to use this command in the console version. 

D:\ChromiumHtmlToPdf_4_2_1\ChromiumHtmlToPdfConsole.exe --multi-threading --input-is-list --input D:\FonteDatiFusion\LUCE5\Schede_tecniche\Schede_x_codice\FRRF001993\list.html --output D:\FonteDatiFusion\LUCE5\Schede_tecniche\Schede_x_codice\FRRF001993\

It gives me this error

2024-12-04T17:11:41.482 - Reading input file 'D:\FonteDatiFusion\LUCE5\Schede_tecniche\Schede_x_codice\FRRF001993\list.html'
2024-12-04T17:11:41.495 - 2 items read
2024-12-04T17:11:41.496 - Starting 8 processing tasks
2024-12-04T17:11:41.501 - Started
2024-12-04T17:11:41.510 - Resetting Chromium arguments to default
2024-12-04T17:11:41.510 - Resetting Chromium arguments to default
2024-12-04T17:11:41.511 - Resetting Chromium arguments to default
2024-12-04T17:11:41.511 - Resetting Chromium arguments to default
2024-12-04T17:11:41.512 - Resetting Chromium arguments to default
2024-12-04T17:11:41.513 - Resetting Chromium arguments to default
2024-12-04T17:11:41.513 - Resetting Chromium arguments to default
2024-12-04T17:11:41.514 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.514 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.515 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.515 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.516 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.516 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.517 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.517 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.517 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.518 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.518 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.519 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.519 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.520 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.521 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.521 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.524 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.524 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.525 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.525 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.526 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.526 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.527 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.527 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.527 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.528 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.528 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.529 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.529 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.530 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.530 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.531 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.532 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.534 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.534 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.535 - Resetting Chromium arguments to default
2024-12-04T17:11:41.535 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.536 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.537 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.537 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.537 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.538 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.539 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.540 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.540 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.541 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.541 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.542 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.543 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.544 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.544 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.545 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.545 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.546 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.546 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.547 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.547 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.548 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.548 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.549 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.549 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.550 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.550 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.551 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.551 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.551 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.552 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.554 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.554 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.555 - Adding Chromium argument '--headless=new'
2024-12-04T17:11:41.555 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.556 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.558 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.558 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.559 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.559 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.560 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.560 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.561 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.561 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.562 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.563 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.564 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.565 - Adding Chromium argument '--block-new-web-contents'
2024-12-04T17:11:41.565 - Adding Chromium argument '--hide-scrollbars'
2024-12-04T17:11:41.566 - Adding Chromium argument '--disable-domain-reliability'
2024-12-04T17:11:41.566 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.567 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.567 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.568 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.568 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.568 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.569 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.569 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.570 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.570 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.571 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.573 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.575 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.575 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.576 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.576 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.577 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.577 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.578 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.578 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.579 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.579 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.580 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.581 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.581 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.582 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.582 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.583 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.583 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.585 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.586 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.586 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.587 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.587 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.588 - 3 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.589 - Adding Chromium argument '--disable-sync'
2024-12-04T17:11:41.590 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.591 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.592 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.593 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.593 - 5 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.595 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.596 - Adding Chromium argument '--mute-audio'
2024-12-04T17:11:41.596 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.597 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.597 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.598 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.598 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.599 - Adding Chromium argument '--disable-background-networking'
2024-12-04T17:11:41.599 - Adding Chromium argument '--disable-background-timer-throttling'
2024-12-04T17:11:41.600 - Adding Chromium argument '--disable-default-apps'
2024-12-04T17:11:41.600 - Adding Chromium argument '--disable-extensions'
2024-12-04T17:11:41.601 - Adding Chromium argument '--disable-hang-monitor'
2024-12-04T17:11:41.601 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.601 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.602 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.602 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.603 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.603 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.604 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.606 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.606 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.607 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.608 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.609 - Adding Chromium argument '--disable-prompt-on-repost'
2024-12-04T17:11:41.609 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.610 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.610 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.611 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.611 - 2 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.612 - Adding Chromium argument '--metrics-recording-only'
2024-12-04T17:11:41.612 - Adding Chromium argument '--no-first-run'
2024-12-04T17:11:41.613 - Adding Chromium argument '--no-default-browser-check'
2024-12-04T17:11:41.613 - 8 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.614 - 1 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.614 - 3 - Starting Google Chrome from location 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files (x86)\Google\Chrome\Application'
2024-12-04T17:11:41.615 - 5 - Starting Google Chrome from location 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files (x86)\Google\Chrome\Application'
2024-12-04T17:11:41.615 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.617 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.618 - Adding Chromium argument '--enable-automation'
2024-12-04T17:11:41.618 - 3 - "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-12-04T17:11:41.619 - 5 - "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless=new --block-new-web-contents --hide-scrollbars --disable-domain-reliability --disable-sync --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --metrics-recording-only --no-first-run --no-default-browser-check --enable-automation --no-pings --noerrdialogs --run-all-compositor-stages-before-draw --remote-debugging-port="0" --window-size="1366,768"
2024-12-04T17:11:41.619 - 2 - Google Chrome closed gracefully
2024-12-04T17:11:41.620 - 8 - Google Chrome closed gracefully
2024-12-04T17:11:41.620 - 1 - Google Chrome closed gracefully
2024-12-04T17:11:41.621 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.622 - 7 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.622 - Adding Chromium argument '--no-pings'
2024-12-04T17:11:41.622 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.624 - Adding Chromium argument '--noerrdialogs'
2024-12-04T17:11:41.624 - 7 - Google Chrome closed gracefully
2024-12-04T17:11:41.625 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.626 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.626 - Adding Chromium argument '--run-all-compositor-stages-before-draw'
2024-12-04T17:11:41.628 - Adding Chromium argument '--remote-debugging-port="0"'
2024-12-04T17:11:41.628 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.629 - Adding Chromium argument '--window-size="1366,768"'
2024-12-04T17:11:41.630 - 4 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.630 - 6 - Updating Chromium argument '--window-size="1366,768"' with value '1366,768'
2024-12-04T17:11:41.630 - 4 - Google Chrome closed gracefully
2024-12-04T17:11:41.631 - 6 - Google Chrome closed gracefully
2024-12-04T17:11:41.637 - 3 - Google Chrome process started
2024-12-04T17:11:41.649 - 5 - Google Chrome process started
2024-12-04T17:11:41.682 -    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at ChromiumHtmlToPdfConsole.Program.Main(String[] args) in C:\Kees\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole\Program.cs:line 0, Could not find a part of the path 'D:\FonteDatiFusion\LUCE5\Schede_tecniche\Schede_x_codice\FRRF001993\'.

I put the destination folder on --output. It seems that this is not accepted.
Can you tell me the correct syntax.
Thanks very much

**Comment by Sicos1977** [comment]
I have no idea what is going wrong.
